name: Scala CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        distribution: adopt
        java-version: 11
    - name: Cache SBT
      uses: actions/cache@v2
      with:
        path: | 
          ~/.ivy2/cache
          ~/.sbt
        key: ${{ runner.os }}-sbt-${{ hashFiles('**/build.sbt') }}-${{ hashFiles('project/Dependencies.scala') }}-${{ hashFiles('project/plugins.sbt') }}
    - name: Run scalafmt
      run: sbt 'scalafmtCheckAll; scalafmtSbtCheck'
    - name: Run scalafix
      run: sbt '++ 2.13.6 scalafix --check'
    - name: Run tests
      run: sbt '+ test'
